### ISSUE TITLE
Query.where() does not accept boolean as per latest types definitions

### ISSUE THREAD

**Issue by pveller** [contentstack/contentstack-javascript#43] opened 2021-01-29 15:45 UTC
I have upgraded to 3.12.1 and the following Typescript code wouldn't compile:

```
stack.ContentType('my_content').Query().where('is_hidden', false),
```

This is due to this type definition:

```
where(key: string, value: (string | number)): Query;
```

The type definitions that I am looking at are:
```
// Type definitions for contentstack 3.12.0
// Project: https://www.contentstack.com/
// Definitions by: Contentstack <https://github.com/contentstack>
```

The implementation in SDK doesn't really care and will be fine with `any`:
https://github.com/contentstack/contentstack-javascript/blob/master/src/core/modules/query.js#L419

I have to do this to "trick" Typescript compiler to believe my code

```
declare module 'contentstack' {
  interface Query {
    where(key: string, value: string | number | boolean): Query;
  }
}
```

**Comment by uttamukkoji** [comment] 2021-02-02 05:49
Hi @pveller, 
Thanks for raising the issue. We will add to support boolean.

**Comment by uttamukkoji** [comment] 2021-02-19 09:12
Hi @pveller ,

The type definition for the `where` function in Query is updated and will now allow to pass `boolean`. 
We release the [JS delivery SDK v3.12.2](https://www.npmjs.com/package/contentstack).

As the issue is resolved we are closing this issue. If you have any concern please feel free to reopen this issue or create issue.

Thanks

**Closed by uttamukkoji** 2021-02-19 09:12 UTC
